name: Danger CI

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  actions: write
  checks: write
  contents: write
  deployments: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  danger:
    runs-on: macos-12
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Update Homebrew
      run: |
        brew update --preinstall
        cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/mint.rb" >> .github/brew-formulae
        cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/xcbeautify.rb" >> .github/brew-formulae

    - name: Select Xcode 14.2
      run: sudo xcode-select -s /Applications/Xcode_14.2.app

    - name: Cache Mint dependencies
      uses: actions/cache@v2
      with:
        path: ~/.mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    - name: Configure Homebrew cache
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/Homebrew/mint--*
          ~/Library/Caches/Homebrew/downloads/*--mint-*
          ~/Library/Caches/Homebrew/xcbeautify--*
          ~/Library/Caches/Homebrew/downloads/*--xcbeautify-*
        key: brew-${{ hashFiles('.github/brew-formulae') }}
        restore-keys: brew-

    - name: Install Homebrew dependencies
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install mint xcbeautify

    - name: Install Mint
      run: |
        make install-mint

    - name: Install build tools via Mint
      run: |
        make mint

    - name: Install xcbeautify
      run: |
        brew update
        rm -f /usr/local/bin/xcbeautify
        brew install xcbeautify

    - name: Generate .xcodeproj file
      run: make xcodegen

    - name: resolvePackagesDependecies 
      run: make packages

    - name: make build 
      run: make build

    - name: Test
      run: |
        make test

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache Node.js dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Danger-JS
      run: npm install -g danger

    - name: Cache Swift dependencies
      uses: actions/cache@v2
      with:
        path: DJSystemiOS-PRLinter/.build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
      if: success() || failure()

    - name: Install Danger and dependencies
      run: |
        cd DJSystemiOS-PRLinter
        swift build

    - name: Run Danger
      run: |
        cd DJSystemiOS-PRLinter
        swift run danger-swift ci --cwd ../
      env:
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}

