name: Danger CI

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  actions: write
  checks: write
  contents: write
  # deployments: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  danger:
    runs-on: macos-12
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Select Xcode 14.2
      run: sudo xcode-select -s /Applications/Xcode_14.2.app
    - name: Install SwiftLint
      run: |
        brew update
        rm -f /usr/local/bin/swiftlint
        brew install swiftlint
        rm -f /usr/local/bin/xcodegen
        brew install xcodegen
        rm -f /usr/local/bin/xcbeautify
        brew install xcbeautify
        rm -f /usr/local/bin/swiftlint
        brew install swiftlint
        rm -f /usr/local/bin/rswift
        brew install rswift

    - name: Generate .xcodeproj file
      run: |
        xcodegen generate
    - name: resolvePackagesDependecies 
      run: make packages
    - name: make build 
      run: make build
    - name: Test
      run: |
        make test
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache Node.js dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Danger-JS
      run: npm install -g danger

    - name: Cache Swift dependencies
      uses: actions/cache@v2
      with:
        path: DJSystemiOS-PRLinter/.build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
      if: success() || failure()


    - name: Install Danger and dependencies
      run: |
        cd DJSystemiOS-PRLinter
        swift build

    - name: Run Danger
      run: |
        echo '{}' >> result.json
        cd DJSystemiOS-PRLinter
        swift run danger-swift ci --cwd ../
      env:
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}

